states_choices <- c(
  "All" = "All",
  "Gujarat" = "Gujarat",
  "Jammu and Kashmir" = "Jammu and Kashmir",
  "Arunachal Pradesh" = "Arunachal Pradesh",
  "Assam" = "Assam",
  "Sikkim" = "Sikkim",
  "West Bengal" = "West Bengal",
  "Uttaranchal" = "Uttaranchal",
  "Uttar Pradesh" = "Uttar Pradesh",
  "Bihar" = "Bihar",
  "Nagaland" = "Nagaland",
  "Manipur" = "Manipur",
  "Mizoram" = "Mizoram",
  "Tripura" = "Tripura",
  "Meghalaya" = "Meghalaya",
  "Punjab" = "Punjab",
  "Rajasthan" = "Rajasthan",
  "Himachal Pradesh" = "Himachal Pradesh",
  "Andhra Pradesh" = "Andhra Pradesh",
  "Orissa" = "Orissa",
  "Daman and Diu" = "Daman and Diu",
  "Maharashtra" = "Maharashtra",
  "Goa" = "Goa",
  "Karnataka" = "Karnataka",
  "Kerala" = "Kerala",
  "Puducherry" = "Puducherry",
  "Tamil Nadu" = "Tamil Nadu",
  "Lakshadweep" = "Lakshadweep",
  "Andaman and Nicobar" = "Andaman and Nicobar",
  "Jharkhand" = "Jharkhand",
  "Delhi" = "Delhi",
  "Dadra and Nagar Haveli" = "Dadra and Nagar Haveli",
  "Chandigarh" = "Chandigarh",
  "Madhya Pradesh" = "Madhya Pradesh",
  "Chhattisgarh" = "Chhattisgarh",
  "Haryana" = "Haryana"
)

states_choices <- states_choices[order(states_choices)]